version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout

      - run:
          name: Install NPM
          command: npm install

      - run:
          name: Test
          command: |
            npm run test
            git status
            git status | grep "nothing to commit, working tree clean"